export const imageConfig = {
    background: {
        earthglobeBg: "/background/earthglobe-bg.webp",
        globeBg: "/background/globe-bg.webp",
        desktop: {
            bgBannerDesktop: "/background/desktop/bg-banner-desktop.webp",
            footerBgDesktop: "/background/desktop/footer-bg-desktop.webp",
            bgDesktop: "/background/desktop/bg-banner-desktop.webp",
            bgDesktopSecondary: "/background/desktop/bg-secondary-desktop.webp",
            bgLoginDesktop: "/background/desktop/bg-login-desktop.webp",
        },
        mobile: {
            bgBannerMobile: "/background/mobile/bg-banner-mobile.webp",
            bgMobile: "/background/mobile/bg-mobile.webp",
            bgMobileSecondary: "/background/mobile/bg-secondary-mobile.webp",
            footerBgMobile: "/background/mobile/footer-bg-mobile.webp",
        },
    },
    icon: {
        cashAdvanceIcon: "/icon/cash-advance-icon.webp",
        chainIcon: "/icon/chain-icon.webp",
        efficientcyIcon: "/icon/efficientcy-icon.webp",
        elementIcon: "/icon/element-icon.webp",
        mapIcon: "/icon/map-icon.webp",
        rwa1Icon: "/icon/rwa-1-icon.webp",
        rwa2Icon: "/icon/rwa-2-icon.webp",
        rwaIcon: "/icon/rwa-icon.webp",
        traceabilityIcon: "/icon/traceability-icon.webp",
        flowerIcon: "/icon/flower-icon.webp",
        profileIcon: "/icon/profile.webp",
        agricultureIcon: "/icon/agricultureIcon.webp",
        assetTokenIcon: "/icon/assetTokenIcon.webp",
        commodityTransactionsIcon: "/icon/commodityTransactionsIcon.webp",
        retailDepotIcon: "/icon/retailDepotIcon.webp",
        commodityListingIcon: "/icon/commodityListingIcon.webp",
        commodityTradingIcon: "/icon/commodityTradingIcon.webp",
        nftMemberIcon: "/icon/nftMemberIcon.webp",
        nftClaimIcon: "/icon/nftClaimIcon.webp",
        stakingIcon: "/icon/stakingIcon.webp",
        userIcon: "/icon/userIcon.webp",
        nftRewardIcon: "/icon/nftCashbackIcon.webp",
        centuryIcon: "/icon/centuryIcon.webp",
        warehouseIcon: "/icon/warehouseIcon.webp",
        aggregatorIcon: "/icon/aggregatorIcon.webp",
        exchangeTradingIcon: "/icon/exchangeTradingIcon.webp",
        marginFeeIcon: "/icon/marginFeeIcon.webp",
        cashbackRewardsIcon: "/icon/cashbackRewardsIcon.webp",
        dataAnalyticsIcon: "/icon/dataAnalyticsIcon.webp",
        distributionFeeIcon: "/icon/distributionFeeIcon.webp",
        insurancePremiumIcon: "/icon/insurancePremiumIcon.webp",
        carbonCreditIcon: "/icon/carbonCreditIcon.webp",
        walletProIcon: "/icon/walletProIcon.webp",
        stablecoinIcon: "/icon/stablecoinIcon.webp",
        ecosystemIcon: "/icon/ecosystemIcon.webp",
        crossBorderIcon: "/icon/crossBorderIcon.webp",
    },
    logo: {
        stomatradeLogo: "/logo/stomatrade-logo.webp",
    },
}
